<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Update all course thumbnails to use the ASTA logo
        DB::table('courses')->update([
            'thumbnail' => 'images/asta.png',
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // This migration cannot be safely reversed as we don't know the original thumbnail paths
        // The original thumbnails were generated by the seeder and may not exist anymore
    }
};
