<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Update all user profile photos to use the ASTA logo
        DB::table('users')->update([
            'profile_photo_path' => 'images/asta.png',
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // This migration cannot be safely reversed as we don't know the original profile photo paths
        // The original photos were generated by the seeder and may not exist anymore
    }
};
